export type CommonMaterialSourceStatus =
  | 'direct_source'
  | 'pdf_direct_source'
  | 'related_source'
  | 'needs_domain'

export interface CommonMaterial {
  id: string
  sourceId: string
  name: string
  nameJa: string
  summary: string
  owner: string
  getFrom: string
  howToGet: string
  timing: string
  commonUses: string[]
  sourceUrl: string
  sourceStatus: CommonMaterialSourceStatus
  domainNote?: string
  displayNote?: string
  aliases?: string[]
}

export const COMMON_MATERIALS: CommonMaterial[] = [
  {
    id: 'juminhyo',
    sourceId: 'M-001',
    name: '住民票',
    nameJa: '住民票の写し',
    summary: '证明在日本的住址和世带构成。手续不同，会要求本人のみ或世帯全員。',
    owner: '本人、扶养人或日本人配偶者取得',
    getFrom: '住所地市区町村窗口；支持时也可便利店交付。',
    howToGet: '窗口申请，或用マイナンバーカード在便利店交付。',
    timing: '多数在留手续按发行后 3 个月以内准备。',
    commonUses: ['家族滞在', '日本人配偶者等', '永住', '住址相关手续'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/dependent.html',
    sourceStatus: 'direct_source',
    displayNote: '永住等手续可能要求“世帯全員記載”。不要只按“住民票”三个字去开。',
    aliases: ['住民票の写し', '世帯全員', '住所证明', '居民票'],
  },
  {
    id: 'resident-tax-income-certificate',
    sourceId: 'M-002',
    name: '课税证明',
    nameJa: '住民税の課税（又は非課税）証明書',
    summary: '证明上一年度所得和课税状况。非课税者通常开非课税证明。',
    owner: '本人、扶养人或配偶者取得',
    getFrom: '1 月 1 日所在地的市区町村窗口。',
    howToGet: '窗口申请；部分自治体支持便利店或线上交付。',
    timing: '按申请路线确认年度；多数在留手续按发行后 3 个月以内准备。',
    commonUses: ['技人国', '经营管理', '家族滞在', '日本人配偶者等', '永住'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/gijinkoku.html',
    sourceStatus: 'direct_source',
    domainNote: '永住所需年数随路线不同，不能一律写成 5 年分。',
    displayNote: '要确认是否同时记载“总所得”和“纳税状况”。',
    aliases: ['課税証明書', '非課税証明書', '所得证明', '住民税证明'],
  },
  {
    id: 'resident-tax-payment-certificate',
    sourceId: 'M-003',
    name: '住民税纳税证明',
    nameJa: '住民税の納税証明書',
    summary: '证明住民税是否已缴纳。和课税证明不是同一种材料。',
    owner: '本人、扶养人或配偶者取得',
    getFrom: '1 月 1 日所在地的市区町村窗口。',
    howToGet: '窗口申请；部分自治体支持便利店或线上交付。',
    timing: '永住等手续要按路线准备直近数年分。',
    commonUses: ['技人国', '经营管理', '家族滞在', '日本人配偶者等', '永住'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/procedures/16-4.html',
    sourceStatus: 'direct_source',
    domainNote: '永住中迟缴、免除、缺年度等影响属于个案判断。',
    displayNote: '不要拿成只显示所得的课税证明。',
    aliases: ['納税証明書', '住民税纳税', '税金证明'],
  },
  {
    id: 'national-tax-certificate-3',
    sourceId: 'M-004',
    name: '国税纳税证明その3',
    nameJa: '納税証明書（その3）',
    summary: '税务署出具的国税未纳证明。永住常见为 5 税目。',
    owner: '本人取得',
    getFrom: '管辖税务署或 e-Tax。',
    howToGet: '税务署窗口申请，或通过 e-Tax 申请。',
    timing: '多数按发行后 3 个月以内准备。',
    commonUses: ['永住', '经营管理'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/procedures/16-4.html',
    sourceStatus: 'direct_source',
    displayNote: '“その1 / その2 / その3”用途不同，永住不要拿错种类。',
    aliases: ['国税', 'その3', '納税証明書その3', '五税目'],
  },
  {
    id: 'koseki-tohon',
    sourceId: 'M-005',
    name: '户籍謄本',
    nameJa: '戸籍謄本（全部事項証明書）',
    summary: '日本人家属的户籍全事项证明，用于证明婚姻或亲子关系。',
    owner: '日本人配偶者或日本人亲属取得',
    getFrom: '日本人本籍地的市区町村窗口。',
    howToGet: '窗口或邮寄申请；部分自治体支持便利店交付。',
    timing: '多数按发行后 3 个月以内准备。',
    commonUses: ['日本人配偶者等', '永住配偶者路线', '家族关系证明'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/spouseorchildofjapanese01.html',
    sourceStatus: 'direct_source',
    domainNote: '外国籍实子路径的亲子关系证明仍需专业或窗口确认。',
    aliases: ['戸籍', '全部事項証明書', '日配'],
  },
  {
    id: 'foreign-marriage-birth-translation',
    sourceId: 'M-006',
    name: '外国婚姻/出生证明和日文翻译',
    nameJa: '婚姻証明書・出生証明書＋日本語翻訳文',
    summary: '外国机关发行的婚姻或出生证明，通常需要附日文翻译。',
    owner: '本人或家属准备',
    getFrom: '本国户籍/登记机关；翻译由本人或翻译者制作。',
    howToGet: '取得原件或复印件后，按窗口要求附日文翻译。',
    timing: '按发行国和窗口要求确认。',
    commonUses: ['家族滞在', '日本人配偶者等', '永住家族关系证明'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/dependent.html',
    sourceStatus: 'direct_source',
    domainNote: '公证翻译、认证、apostille 是否需要，取决于手续和发行国。',
    displayNote: '不要一律断言“必须公证翻译”。',
    aliases: ['结婚证', '出生证明', '翻译', '婚姻証明書', '出生証明書'],
  },
  {
    id: 'employment-certificate',
    sourceId: 'M-007',
    name: '在职证明',
    nameJa: '在職証明書',
    summary: '公司出具的在籍、职位、业务内容等证明。',
    owner: '雇用公司准备',
    getFrom: '公司人事或总务。',
    howToGet: '向公司申请，按用途写明职位、期间、业务内容等。',
    timing: '建议用最新版本，通常申请前 3 个月以内。',
    commonUses: ['家族滞在', '永住', '技人国', '工作经历证明'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/gijinkoku.html',
    sourceStatus: 'direct_source',
    aliases: ['在職証明', '工作证明', '公司证明'],
  },
  {
    id: 'labor-conditions-notice',
    sourceId: 'M-008',
    name: '劳动条件通知书',
    nameJa: '労働条件通知書（雇用契約書）',
    summary: '记载职位、业务内容、工资、勤務地等雇用条件的文件。',
    owner: '雇用公司准备',
    getFrom: '公司人事。',
    howToGet: '入社或内定时由公司交付；雇用契约书内容同等时可使用。',
    timing: '用反映当前雇用条件的最新版。',
    commonUses: ['技人国变更', '转职后技人国更新', '派遣技人国'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/gijinkoku.html',
    sourceStatus: 'direct_source',
    aliases: ['雇用契約書', '合同', '労働条件', '工作合同'],
  },
  {
    id: 'withholding-slip',
    sourceId: 'M-009',
    name: '源泉徴収票/法定调书合计表',
    nameJa: '源泉徴収票・法定調書合計表',
    summary: '个人的源泉徴収票和公司提交的法定调书合计表是不同材料。',
    owner: '个人源泉票由公司给本人；法定调书合计表由公司准备。',
    getFrom: '公司人事、总务或会计。',
    howToGet: '个人源泉票通常年初交付；公司侧材料需向公司内部申请。',
    timing: '按上一年度或最新年度准备。',
    commonUses: ['技人国类别证明', '经营管理类别证明', '收入证明'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/gijinkoku.html',
    sourceStatus: 'direct_source',
    displayNote: '不要把个人源泉徴収票和公司法定调书合计表混用。',
    aliases: ['源泉票', '源泉徴収', '法定調書', '合计表'],
  },
  {
    id: 'company-registry',
    sourceId: 'M-010',
    name: '公司登记事项证明书',
    nameJa: '登記事項証明書',
    summary: '法务局发行的法人登记证明，记载公司名称、地址、代表者等。',
    owner: '公司准备',
    getFrom: '法务局或登記ねっと。',
    howToGet: '窗口、邮寄或线上申请。',
    timing: '多数按发行后 3 个月以内准备。',
    commonUses: ['技人国', '经营管理', '公司资料'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/gijinkoku.html',
    sourceStatus: 'direct_source',
    aliases: ['登記簿', '法人登记', '登記事項'],
  },
  {
    id: 'financial-statements',
    sourceId: 'M-011',
    name: '最近年度决算书',
    nameJa: '直近年度の決算文書の写し',
    summary: '公司最近年度的财务资料，如贷借对照表、损益计算书等。',
    owner: '公司或税理士准备',
    getFrom: '公司内部、会计或税理士。',
    howToGet: '提交公司保存的申报/决算资料复印件。',
    timing: '使用最近一个已完成年度。',
    commonUses: ['技人国 Cat3/4', '经营管理'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/gijinkoku.html',
    sourceStatus: 'direct_source',
    displayNote: '新设公司是否可用事业计划书替代，按手续确认。',
    aliases: ['決算書', '财务报表', '貸借対照表', '損益計算書'],
  },
  {
    id: 'business-overview',
    sourceId: 'M-012',
    name: '事业内容说明资料',
    nameJa: '事業内容を明らかにする文書',
    summary: '说明公司沿革、组织、业务内容、主要客户等的资料。',
    owner: '公司准备',
    getFrom: '公司内部资料、公司简介、网站打印件等。',
    howToGet: '已有公司简介可使用；没有时可用任意格式整理。',
    timing: '使用反映最新业务内容的版本。',
    commonUses: ['技人国 Cat3/4', '经营管理'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/gijinkoku.html',
    sourceStatus: 'direct_source',
    aliases: ['会社案内', 'パンフレット', '事業内容案内書', '公司简介'],
  },
  {
    id: 'activity-explanation',
    sourceId: 'M-013',
    name: '活动内容说明/理由书',
    nameJa: '活動内容を具体的に説明する文書・理由書',
    summary: '用任意格式说明业务内容、申请理由或经营活动情况。',
    owner: '本人、公司或经营者准备',
    getFrom: '自行制作或由公司协助制作。',
    howToGet: '按申请目的整理事实，不在材料页判断写法是否充分。',
    timing: '反映申请时点的最新情况。',
    commonUses: ['技人国', '经营管理', '永住理由书'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/businessmanager.html',
    sourceStatus: 'direct_source',
    domainNote: '理由书写法、业务适合性、经营实态说明属于个案判断。',
    aliases: ['理由書', '说明书', '活動内容説明書'],
  },
  {
    id: 'photo-passport-residence-card',
    sourceId: 'M-014',
    name: '照片、护照、在留卡',
    nameJa: '写真・パスポート・在留カード',
    summary: '多数在留申请共通的本人确认材料。',
    owner: '本人准备',
    getFrom: '照片在照相馆或证件照机器；护照和在留卡由本人持有。',
    howToGet: '照片按入管规格准备；护照和在留卡通常递交时提示原件。',
    timing: '照片通常为申请前 6 个月以内。',
    commonUses: ['几乎所有在留申请'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/procedures/16-3.html',
    sourceStatus: 'direct_source',
    displayNote: '护照和在留卡很多手续是“提示”，不是提交后被收走。',
    aliases: ['写真', '护照', 'パスポート', '在留カード', '证件照'],
  },
  {
    id: 'pension-record',
    sourceId: 'M-015',
    name: '年金记录',
    nameJa: '被保険者記録照会回答票・ねんきんネット',
    summary: '证明年金加入和纳付情况的资料。',
    owner: '本人取得',
    getFrom: '年金事务所或ねんきんネット。',
    howToGet: '窗口请求被保险者记录照会，或从ねんきんネット打印。',
    timing: '永住等通常用直近期间，按路线确认。',
    commonUses: ['永住', '税年金风险确认'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/procedures/16-4.html',
    sourceStatus: 'direct_source',
    domainNote: '正式免除・猶予期间对永住审查影响仍需专业确认。',
    displayNote: '不要把“免除/猶予”说成和“缴纳完毕”完全相同。',
    aliases: ['年金', 'ねんきんネット', '被保険者記録', '国民年金'],
  },
  {
    id: 'health-insurance-proof',
    sourceId: 'M-016',
    name: '健康保险资格资料',
    nameJa: '健康保険被保険者証・資格確認資料',
    summary: '证明加入健康保险或国民健康保险的资料。',
    owner: '本人取得',
    getFrom: '公司、健保组合、市区町村或マイナポータル。',
    howToGet: '按当前保险类型准备资格确认资料或相关截图/证明。',
    timing: '使用申请时有效的资料。',
    commonUses: ['永住', '公的义务确认'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/procedures/16-4.html',
    sourceStatus: 'direct_source',
    displayNote: 'マイナ保険証后，传统保险证和资格确认资料的替代关系要按最新页面确认。',
    aliases: ['健康保険', '国保', '健保', '資格確認証', 'マイナ保険証'],
  },
  {
    id: 'bank-balance-certificate',
    sourceId: 'M-017',
    name: '存款余额证明',
    nameJa: '預金残高証明書',
    summary: '银行出具的账户余额证明，用于说明生活费或资产。',
    owner: '本人、扶养人或配偶者取得',
    getFrom: '开户银行。',
    howToGet: '向银行申请残高证明；部分场景可用通账复印件替代。',
    timing: '建议临近申请取得，窗口可能要求较新版本。',
    commonUses: ['家族滞在', '留学', '日本人配偶者等', '永住资产证明'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/dependent.html',
    sourceStatus: 'direct_source',
    aliases: ['残高証明', '银行存款证明', '通帳'],
  },
  {
    id: 'scholarship-certificate',
    sourceId: 'M-018',
    name: '奖学金证明',
    nameJa: '奨学金の給付に関する証明書',
    summary: '证明奖学金金额和给付期间的文件。',
    owner: '奖学金机构或学校发行',
    getFrom: 'JASSO、学校或奖学金机构。',
    howToGet: '按机构流程申请证明书。',
    timing: '使用能覆盖当前申请期间的证明。',
    commonUses: ['留学', '家族滞在无就劳收入分支'],
    sourceUrl: 'https://www.moj.go.jp/isa/applications/status/student.html',
    sourceStatus: 'direct_source',
    aliases: ['奨学金', '奖学金', 'JASSO'],
  },
  {
    id: 'guarantor-letter',
    sourceId: 'M-019',
    name: '身元保证书',
    nameJa: '身元保証書',
    summary: '保证人按 ISA 所定样式填写并签名的文件。',
    owner: '保证人填写',
    getFrom: 'ISA 官网下载样式。',
    howToGet: '下载表格后由保证人填写、签名。',
    timing: '申请时准备新版签名文件。',
    commonUses: ['永住', '日本人配偶者等'],
    sourceUrl: 'https://www.moj.go.jp/isa/content/930002536.pdf',
    sourceStatus: 'direct_source',
    domainNote: '保证人资格、收入、在留卡期限等具体判断不要在材料页断言。',
    aliases: ['身元保証', '保证人', '保証書'],
  },
  {
    id: 'eijuu-ryokaisho',
    sourceId: 'M-020',
    name: '永住了解书',
    nameJa: '了解書',
    summary: '永住申请中确认理解永住取消制度等内容的所定样式。',
    owner: '申请人本人签署',
    getFrom: 'ISA 官网下载，多语言版本可用。',
    howToGet: '下载对应语言表格，由本人填写签名。',
    timing: '申请时按最新样式准备。',
    commonUses: ['永住'],
    sourceUrl: 'https://www.moj.go.jp/isa/content/001355579.pdf',
    sourceStatus: 'direct_source',
    displayNote: '了解书内容涉及永住取消制度，详细解释应进入专业边界。',
    aliases: ['了解書', '永久了解书', '永住取消'],
  },
]

export function getCommonMaterial(id: string) {
  return COMMON_MATERIALS.find((material) => material.id === id)
}

export function searchCommonMaterials(query: string) {
  const normalizedQuery = normalizeMaterialText(query)
  if (!normalizedQuery) return COMMON_MATERIALS
  return COMMON_MATERIALS.filter((material) =>
    normalizeMaterialText(commonMaterialSearchText(material)).includes(
      normalizedQuery,
    ),
  )
}

export function commonMaterialSearchText(material: CommonMaterial) {
  return [
    material.name,
    material.nameJa,
    material.summary,
    material.owner,
    material.getFrom,
    material.howToGet,
    material.timing,
    material.displayNote ?? '',
    material.domainNote ?? '',
    ...material.commonUses,
    ...(material.aliases ?? []),
  ].join(' ')
}

function normalizeMaterialText(value: string) {
  return value.trim().toLowerCase().replace(/\s+/g, '')
}
