import { VisaTypeConfig } from '@/types/session'

export const VISA_TYPES: Record<string, VisaTypeConfig> = {
  work: {
    id: 'work',
    label: 'Work Visa',
    description: 'Engineer / Specialist in Humanities / International Services',
    price: 9800,
    referralConditions: ['Residence period less than 1 year', 'History of denial', 'First renewal after job change'],
    materials: [
      { name: 'Passport (original + copy)' },
      { name: 'Residence Card (original + copy)' },
      { name: 'Resident Certificate (within 3 months)' },
      { name: 'Employment Certificate or Job Offer Letter' },
      { name: 'Withholding Tax Certificate (last 1 year)' },
      { name: 'Company Registration Certificate' },
      { name: 'Company Financial Statements (last 2 years)' },
      { name: 'Reason Statement', conditional: true, condition: 'If changing jobs or job type' },
      { name: 'Resignation Certificate from Previous Employer', conditional: true, condition: 'If changed jobs' },
    ],
    submissionSteps: [
      { step: 1, title: 'Prepare Documents', description: 'Gather all documents and make copies' },
      { step: 2, title: 'Submit to Immigration Bureau', description: 'Submit at the counter of your jurisdiction (mail may be available)' },
      { step: 3, title: 'Wait for Review', description: 'Standard processing: 2 weeks to 3 months' },
      { step: 4, title: 'Receive Result', description: 'If approved, receive new Residence Card' },
    ],
  },
  spouse: {
    id: 'spouse',
    label: 'Spouse Visa',
    description: 'Spouse of Japanese national or permanent resident',
    price: 9800,
    referralConditions: ['Short marriage period', 'Living separately', 'Low Japanese proficiency'],
    materials: [
      { name: 'Passport (original + copy)' },
      { name: 'Residence Card (original + copy)' },
      { name: 'Resident Certificate (within 3 months)' },
      { name: 'Family Register of Japanese spouse' },
      { name: 'Marriage Certificate (with translation if foreign)' },
      { name: "Spouse's Municipal Tax Certificate" },
      { name: "Spouse's Withholding Tax Certificate" },
      { name: 'Photos of couple (multiple)' },
      { name: 'Questionnaire (immigration designated form)' },
      { name: 'Reason Statement', conditional: true, condition: 'If living separately or long absence from Japan' },
    ],
    submissionSteps: [
      { step: 1, title: 'Prepare Documents', description: 'Gather documents from both Japanese and foreign side' },
      { step: 2, title: 'Submit to Immigration Bureau', description: 'Submit at the counter of your jurisdiction' },
      { step: 3, title: 'Wait for Review', description: 'Standard processing: 1 to 3 months' },
      { step: 4, title: 'Receive Result', description: 'If approved, receive new Residence Card' },
    ],
  },
  permanent: {
    id: 'permanent',
    label: 'Permanent Residence',
    description: 'Application for permanent residency',
    price: 14800,
    referralConditions: ['Less than 10 years in Japan', 'Unpaid taxes or pension', 'Past immigration violations'],
    materials: [
      { name: 'Passport (original + copy)' },
      { name: 'Residence Card (original + copy)' },
      { name: 'Resident Certificate (all household members)' },
      { name: 'Municipal Tax Certificate (last 3 years)' },
      { name: 'Municipal Tax Payment Certificate (last 3 years)' },
      { name: 'Pension Payment Certificate' },
      { name: 'Health Insurance Card (original + copy)' },
      { name: 'Employment or Business Certificate' },
      { name: 'Withholding Tax Certificate (last 3 years)' },
      { name: 'Guarantor Letter (Japanese national or permanent resident)' },
      { name: 'Reason Statement' },
    ],
    submissionSteps: [
      { step: 1, title: 'Prepare Documents', description: 'Gather 3 years of tax and pension documents (most time-consuming)' },
      { step: 2, title: 'Submit to Immigration Bureau', description: 'Must submit in person at your jurisdiction (no mail)' },
      { step: 3, title: 'Wait for Review', description: 'Standard processing: 4 months to 1 year' },
      { step: 4, title: 'Receive Result', description: 'If approved, receive Permanent Residence Card' },
    ],
  },
  student: {
    id: 'student',
    label: 'Student Visa',
    description: 'Enrollment at school or university',
    price: 7800,
    referralConditions: ['Low attendance rate', 'Changing schools'],
    materials: [
      { name: 'Passport (original + copy)' },
      { name: 'Residence Card (original + copy)' },
      { name: 'Resident Certificate (within 3 months)' },
      { name: 'Enrollment Certificate (issued by school)' },
      { name: 'Academic Transcript' },
      { name: 'Attendance Certificate (issued by school)' },
      { name: 'Financial Support Certificate (remittance proof etc.)' },
      { name: 'Reason Statement', conditional: true, condition: 'If changing schools' },
    ],
    submissionSteps: [
      { step: 1, title: 'Prepare Documents', description: 'Obtain certificates from your current school' },
      { step: 2, title: 'Submit to Immigration Bureau', description: 'Submit at the counter of your jurisdiction' },
      { step: 3, title: 'Wait for Review', description: 'Standard processing: 2 weeks to 2 months' },
      { step: 4, title: 'Receive Result', description: 'If approved, receive new Residence Card' },
    ],
  },
}

export const VISA_TYPE_LIST = Object.values(VISA_TYPES)
