import { VisaTypeConfig } from '@/types/session'

export const VISA_TYPES: Record<string, VisaTypeConfig> = {
  work: {
    id: 'work',
    label: '就労ビザ',
    description: '技術・人文知識・国際業務など',
    price: 9800,
    referralConditions: ['前回の在留期間が1年未満', '不許可歴あり', '転職後初回更新'],
    materials: [
      { name: 'パスポート（原本＋コピー）' },
      { name: '在留カード（原本＋コピー）' },
      { name: '住民票（3ヶ月以内）' },
      { name: '在職証明書または採用内定通知書' },
      { name: '源泉徴収票（直近1年分）' },
      { name: '会社の登記事項証明書' },
      { name: '会社の決算書（直近2期分）' },
      { name: '申請理由書', conditional: true, condition: '転職・職種変更の場合' },
      { name: '前職の退職証明書', conditional: true, condition: '転職の場合' },
    ],
    submissionSteps: [
      { step: 1, title: '書類の準備', description: '全書類を揃え、コピーを取る' },
      { step: 2, title: '出入国在留管理局へ提出', description: '管轄の入管局の窓口に提出（郵送可の場合あり）' },
      { step: 3, title: '審査待ち', description: '標準処理期間：2週間〜3ヶ月' },
      { step: 4, title: '結果通知', description: '許可の場合は在留カードを受け取る' },
    ],
  },
  spouse: {
    id: 'spouse',
    label: '配偶者ビザ',
    description: '日本人・永住者の配偶者',
    price: 9800,
    referralConditions: ['婚姻期間が短い', '別居中', '日本語能力が低い'],
    materials: [
      { name: 'パスポート（原本＋コピー）' },
      { name: '在留カード（原本＋コピー）' },
      { name: '住民票（3ヶ月以内）' },
      { name: '戸籍謄本（日本人配偶者）' },
      { name: '婚姻証明書（外国語の場合は翻訳付き）' },
      { name: '配偶者の住民税課税証明書' },
      { name: '配偶者の源泉徴収票' },
      { name: '夫婦の写真（複数枚）' },
      { name: '質問書（入管指定様式）' },
      { name: '理由書', conditional: true, condition: '別居・長期離日の場合' },
    ],
    submissionSteps: [
      { step: 1, title: '書類の準備', description: '日本側・外国側双方の書類を揃える' },
      { step: 2, title: '出入国在留管理局へ提出', description: '管轄の入管局の窓口に提出' },
      { step: 3, title: '審査待ち', description: '標準処理期間：1〜3ヶ月' },
      { step: 4, title: '結果通知', description: '許可の場合は在留カードを受け取る' },
    ],
  },
  permanent: {
    id: 'permanent',
    label: '永住許可',
    description: '永住権の取得申請',
    price: 14800,
    referralConditions: ['在留期間が10年未満', '税金・年金の未納あり', '過去に在留違反あり'],
    materials: [
      { name: 'パスポート（原本＋コピー）' },
      { name: '在留カード（原本＋コピー）' },
      { name: '住民票（世帯全員）' },
      { name: '住民税課税証明書（過去3年分）' },
      { name: '住民税納税証明書（過去3年分）' },
      { name: '年金保険料納付証明書' },
      { name: '健康保険証（原本＋コピー）' },
      { name: '在職証明書または事業証明書' },
      { name: '源泉徴収票（直近3年分）' },
      { name: '身元保証書（日本人または永住者）' },
      { name: '理由書' },
    ],
    submissionSteps: [
      { step: 1, title: '書類の準備', description: '過去3年分の税・年金書類を揃える（最も時間がかかる）' },
      { step: 2, title: '出入国在留管理局へ提出', description: '管轄の入管局の窓口に直接提出（郵送不可）' },
      { step: 3, title: '審査待ち', description: '標準処理期間：4ヶ月〜1年' },
      { step: 4, title: '結果通知', description: '許可の場合は永住カードを受け取る' },
    ],
  },
  student: {
    id: 'student',
    label: '留学ビザ',
    description: '学校・大学への在籍',
    price: 7800,
    referralConditions: ['出席率が低い', '学校を変更する'],
    materials: [
      { name: 'パスポート（原本＋コピー）' },
      { name: '在留カード（原本＋コピー）' },
      { name: '住民票（3ヶ月以内）' },
      { name: '在学証明書（学校発行）' },
      { name: '成績証明書' },
      { name: '出席率証明書（学校発行）' },
      { name: '経費支弁証明書（送金証明など）' },
      { name: '理由書', conditional: true, condition: '学校変更の場合' },
    ],
    submissionSteps: [
      { step: 1, title: '書類の準備', description: '在学中の学校から証明書を取得する' },
      { step: 2, title: '出入国在留管理局へ提出', description: '管轄の入管局の窓口に提出' },
      { step: 3, title: '審査待ち', description: '標準処理期間：2週間〜2ヶ月' },
      { step: 4, title: '結果通知', description: '許可の場合は在留カードを受け取る' },
    ],
  },
}

export const VISA_TYPE_LIST = Object.values(VISA_TYPES)
